version: '3'

services:
  servercontainer:
    build:
      context: ./server
    ports:
      - "3000:3000"
    restart: always
    # Add other container1 configuration options as needed

  clientcontainer:
    build:
      context: ./frontend
    ports:
      - "8000:8000"
    # Add other container2 configuration options as needed

